trigger: none

pr: none

resources:
  repositories:
  - repository: pnp-deploy-repo-automation
    type: git
    project: Platform and Process
    name: pnp-deploy-repo-automation
    ref: refs/heads/tst-adf-branch
    trigger:
      branches:
        include:
          - main
  - repository: pnp-pipelines-automation
    type: git
    project: Platform and Process
    name: pnp-pipelines-automation
    ref: refs/heads/ADF-bkp


stages:
  - stage: Deployresource
    displayName: 'Deploy Resource'
    jobs:
      - job: Deploy
        pool:
          name: vmss-dm-pp-prd-we-1
        container:
          image: crdmppbasewe1.azurecr.io/facade-template-tf-module-env_pnp:main
          endpoint: crdmppbasewe1
          options: --user 0:0

        steps:
        - checkout: self
        - checkout: pnp-deploy-repo-automation
          persistCredentials: true
          fetchDepth: 2

        - task: Bash@3
          displayName: 'Login and fetch token'
          inputs:
            targetType: 'filePath'
            filePath: './pnp-pipelines-automation/scripts/common/get-token.sh'
            workingDirectory: '$(Build.SourcesDirectory)/pnp-deploy-repo-automation'

        - task: Bash@3
          displayName: "Detect changed folders"
          inputs:
            targetType: 'filePath'
            filePath: './pnp-pipelines-automation/scripts/common/detect-changed-folders.sh'
            workingDirectory: '$(Build.SourcesDirectory)/pnp-deploy-repo-automation'

        - task: Bash@3
          displayName: "Apply in changed folders"
          inputs:
            targetType: 'filePath'
            filePath: './pnp-pipelines-automation/scripts/common/apply-in-changed-folders.sh'
            workingDirectory: '$(Build.SourcesDirectory)/pnp-deploy-repo-automation'
          env:
              ENCODED_PAT: $(ENCODED_PAT)
              AZURE_DEVOPS_EXT_PAT: $(PAT)
              GIT_TERMINAL_PROMPT: 0