trigger:
- main

resources:
  repositories:
  - repository: pnp-deploy-repo-automation
    type: git
    project: Platform and Process
    name: pnp-deploy-repo-automation
    ref: refs/heads/main
  - repository: pnp-pipelines-automation
    type: git
    project: Platform and Process
    name: pnp-pipelines-automation
    branches:
      include:
        - add-repo-automation

pool: 'vmss-dm-pp-prd-we-1'

parameters:
  - name: repository_name
    type: string
    default: 'demo-automation-01'
  - name: project_name
    type: string
    default: 'Platform and Process'
  - name: build_pipeline
    type: string
    default: 'false'
  - name: deploy_pipeline
    type: string
    default: 'false'

steps:
- checkout: self
- checkout: pnp-deploy-repo-automation
  persistCredentials: true

#- task: Bash@3
#  displayName: 'Generate terragrunt configuration.'
#  inputs:
#    targetType: 'filePath'
#    filePath: './pnp-pipelines-automation/scripts/azdo-repository/generate-terragrunt.sh'
#    arguments: '${{parameters.repository_name}} ${{parameters.project_name}}'
#    workingDirectory: '$(Build.SourcesDirectory)/pnp-deploy-repo-automation'

- task: Bash@3
  displayName: 'Generate terraform code'
  inputs:
    targetType: 'filePath'
    filePath: './pnp-pipelines-automation/scripts/azdo-repository/generate-terraform.sh'
    arguments: '"${{ parameters.repository_name }}" "${{ parameters.project_name }}" "${{ parameters.build_pipeline }}" "${{ parameters.deploy_pipeline }}"'
    workingDirectory: '$(Build.SourcesDirectory)/pnp-deploy-repo-automation'

- task: Bash@3
  displayName: 'Commit and push changes'
  inputs:
    targetType: 'filePath'
    filePath: './pnp-pipelines-automation/scripts/azdo-repository/commit-and-push.sh'
    arguments: '${{parameters.repository_name}} ${{parameters.project_name}}'
    workingDirectory: '$(Build.SourcesDirectory)/pnp-deploy-repo-automation'

- script: |
    python3 ./pnp-pipelines-automation/scripts/common/create-pull-request.py \
      --repository_id "pnp-deploy-repo-automation" \
      --source_branch "${{parameters.repository_name}}"
  displayName: "Run Python Script to Create PR"
  env:
    ENCODED_PAT: $(ENCODED_PAT)